# Generated by Django 5.2.12 on 2026-03-19 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegios',
            fields=[
                ('id_colegio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_colegio', models.CharField(max_length=255)),
                ('codigo_dane', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ubicacion_sede', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colegios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PadronAlumnos',
            fields=[
                ('num_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=10)),
                ('nombre_alumno', models.CharField(max_length=255)),
                ('grado_actual', models.IntegerField()),
            ],
            options={
                'db_table': 'padron_alumnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PadronProfesores',
            fields=[
                ('num_doc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=10)),
                ('nombre_completo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'padron_profesores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('num_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('user_type', models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('admin', 'Administrador')], max_length=10, verbose_name='Tipo de usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth_users',
            },
        ),
        migrations.CreateModel(
            name='SolicitudAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor')], max_length=10)),
                ('num_documento', models.CharField(max_length=20)),
                ('tipo_doc', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('validado_contra_padron', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Acceso',
                'verbose_name_plural': 'Solicitudes de Acceso',
                'db_table': 'solicitudes_acceso',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='PerfilProfesor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_profesor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_doc', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_expedicion', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=100)),
                ('estado_acc_profe', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('id_colegio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.colegios')),
                ('padron', models.ForeignKey(db_column='num_doc', on_delete=django.db.models.deletion.PROTECT, to='Auth.padronprofesores')),
            ],
            options={
                'verbose_name': 'Perfil de Profesor',
                'verbose_name_plural': 'Perfiles de Profesores',
                'db_table': 'perfiles_profesores',
            },
        ),
        migrations.CreateModel(
            name='PerfilAlumno',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_alumno', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_doc', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_expedicion', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('grado_actual', models.IntegerField()),
                ('anio_vigencia', models.IntegerField()),
                ('estado_alumno', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('id_colegio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.colegios')),
                ('padron', models.ForeignKey(db_column='num_documento', on_delete=django.db.models.deletion.PROTECT, to='Auth.padronalumnos')),
            ],
            options={
                'verbose_name': 'Perfil de Alumno',
                'verbose_name_plural': 'Perfiles de Alumnos',
                'db_table': 'perfiles_alumnos',
            },
        ),
        migrations.CreateModel(
            name='ProfesorGrados',
            fields=[
                ('id_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('grado_asignado', models.IntegerField()),
                ('anio_lectivo', models.IntegerField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_asignados', to='Auth.perfilprofesor')),
            ],
            options={
                'db_table': 'profesor_grados',
                'unique_together': {('profesor', 'grado_asignado', 'anio_lectivo')},
            },
        ),
    ]
